language: python
python:
  - "3.12"

services:
  - docker

branches:
  only:
    - master

stages:
  - test
  - build and deploy

env:
  global:
    - DOCKER_REPOSITORY=devops-challenge-app
    - COMMIT_TAG=${TRAVIS_COMMIT:0:7}

jobs:
  include:
    - stage: test
      name: Run Unit Tests
      install:
        - pip install -r requirements.txt
      script:
        - PYTHONPATH=./app pytest

    - stage: build and deploy
      name: Build and deploy Application
      install: skip
      script:
        - docker build -t $DOCKER_REPOSITORY .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag $DOCKER_REPOSITORY:latest $DOCKER_USERNAME/$DOCKER_REPOSITORY:latest
        - docker tag $DOCKER_REPOSITORY:latest $DOCKER_USERNAME/$DOCKER_REPOSITORY:$COMMIT_TAG-$TRAVIS_BUILD_NUMBER
        - docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:latest
        - docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:$COMMIT_TAG-$TRAVIS_BUILD_NUMBER