language: python
python:
  - "3.12"

services:
  - docker

branches:
  only:
    - master

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      name: Run Unit Tests
      before_install:
        - pip install pytest
      script:
        - echo "Using port: $CODE_NAME"
        - PYTHONPATH=./app pytest

    - stage: deploy
      name: Deploy to Production
      script:
        - echo "Deploying application..."