language: python
python:
  - "3.12"

services:
  - docker

branches:
  only:
    - master

env:
  global:
    - DOCKER_REPOSITORY=devops-challenge-app
    - COMMIT_TAG=${TRAVIS_COMMIT:0:7}

install:
  - pip install -r requirements.txt
  - pip install pytest

test:
  - PYTHONPATH=./app pytest

build:
  - docker build -t $DOCKER_USERNAME/devops-challenge .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
    - docker tag "$DOCKER_REPOSITORY:latest" "$DOCKER_USERNAME/$DOCKER_REPOSITORY:latest"
    - docker tag "$DOCKER_REPOSITORY:latest" "$DOCKER_USERNAME/$DOCKER_REPOSITORY:$COMMIT_TAG-TRAVIS_BUILD_NUMBER"
    - docker push "$DOCKER_USERNAME/$DOCKER_REPOSITORY:latest"
    - docker push "$DOCKER_USERNAME/$DOCKER_REPOSITORY:$COMMIT_TAG-TRAVIS_BUILD_NUMBER"