services:
  devops_challenge_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devops_challenge_api_app
    env_file:
      - .env
    ports:
      - "${HOST_PORT:-5000}:${PORT:-5000}"
    restart: unless-stopped
    networks:
      - devops_challenge_network

networks:
  devops_challenge_network:
    driver: bridge